maintainer        "Joshua Sierles"
maintainer_email  "joshua@diluvia.net"
description       "Configures nagios"
version           "0.2"
depends           "fcgiwrap"
depends           "nginx"
depends           "ssl_certificates"
depends           "users"