maintainer        "Joshua Sierles"
maintainer_email  "joshua@diluvia.net"
description       "Configures rails apps"
version           "0.2"
depends           "users"
depends           "unicorn"
depends           "logrotate"
depends           "bluepill"
depends           "ssl_certificates"
depends           "bundler"
depends           "nginx"