maintainer        "Joshua Sierles"
maintainer_email  "joshua@diluvia.net"
description       "Configures chef"
version           "0.8"
depends           "logrotate"
depends           "apache2"
depends           "openssl"
depends           "couchdb"
depends           "unicorn"
depends           "ssl_certificates"
depends           "rabbitmq"
depends           "bluepill"