maintainer        "Joshua Sierles"
maintainer_email  "joshua@diluvia.net"
description       "Configures chef"
version           "0.9"
depends           "runit"
depends           "logrotate"
depends           "openssl"
depends           "couchdb"
depends           "unicorn"
depends           "ssl_certificates"
depends           "rabbitmq"
depends           "bluepill"
